server:
  port: 9002

#datasource configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_location
    username: root
    password: root
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
  boot.message: Hello sir,location updated Service    
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest        

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
